name: auto-handle-gitbook
on: 
  push:
    branches:
    - main

jobs:
  main-to-gh-pages:
    runs-on: ubuntu-latest
        
    steps:
    - name: checkout main
      uses: actions/checkout@v2
      with:
        ref: main
            
    - name: install nodejs
      uses: actions/setup-node@v1
      
    - name: configue gitbook
      run: |
        npm install -g gitbook-cli
        gitbook install
        npm install -g gitbook-summary
                
    - name: generate _book
      run: |
        book sm
        gitbook build
                
    - name: push _book to gh-pages
      env:
        TOKEN: ${{ secrets.TOKEN }}
        REF: github.com/wangzhebufangqi/ActionTest.git
      run: |
        cd _book
        git config --global user.email "1823636309@qq.com"
        git config --global user.name "wangzhebufangqi"
        git init
        git remote add origin https://${REF}
        git add . 
        git commit -m "Updated By Github Actions For Github Pages"
        git branch -M main
        git push --force --quiet "https://${TOKEN}@${REF}" main:gh-pages
                
                
                